name: npm github pages
inputs:
  app-name:
    description: "application name"
    required: true
runs:
  using: "composite"
  steps:
  - name: install dependencies
    shell: bash
    run: npm install
  - name: build project
    shell: bash
    run: npm run build -- --base-href ${{ inputs.app-name }}
  - uses: actions/configure-pages@v5
  - uses: actions/upload-pages-artifact@v3
    with:
      path: './dist/${{ inputs.app-name }}'
  - uses: actions/deploy-pages@v4
