name: npm GitHub Pages
inputs:
  project:
    description: "The name of the project to be deployed to GitHub Pages"
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/configure-pages@v5
  - uses: actions/upload-pages-artifact@v3
    with:
      path: './dist/${{ inputs.project }}'
  - uses: actions/deploy-pages@v4