name: Build NPM Project
inputs:
  base-href:
    description: "HTML base href"
    required: false
runs:
  using: "composite"
  steps:
  - name: Install Project Dependencies
    shell: bash
    run: npm install
  - name: Build Project
    shell: bash
    run: npm run build ${{ inputs.base-href && format('-- --base-href {0}', inputs.base-href) }} #-- --key=value