name: Build NPM Project
inputs:
  args:
    description: "npm build arguments"
    required: false
runs:
  using: "composite"
  steps:
  - name: Install Project Dependencies
    shell: bash
    run: npm install
  - name: Build Project
    shell: bash
    run: npm run build ${{ inputs.args && format('-- P{0}', inputs.args) }} #-- --key=value