name: release notes
inputs:
  version:
    description: "npm|mvn project version"
    required: true
runs:
  using: "composite"
  steps:
  - name: create release
    run: gh release create "v${{ inputs.version }}" --repo="${{ github.repository }}" --target="${{ github.ref_name }}" --title="v${{ inputs.version }}" --generate-notes
    shell: bash
