name: Deploy project
inputs:
  organization:
    description: "npm organization"
    required: false
    default: "oneteme"
  package:
    discription: "package name"
    required: false
runs:
  using: "composite"
  steps:
  - name: install dependencies
    shell: bash
    run: npm install
  - name: build project
    shell: bash
    run: npm run build ${{ inputs.package && format('@{0}/{1}', inputs.organization, inputs.package) || '' }}
  - uses: SonarSource/sonarqube-scan-action@v4.2.1
