name: Extract project version
inputs:
  path:
    description: "package.json file path" 
    required: false
    default: "./package.json"
outputs:
  version:
    description: "project version"
    value: ${{ steps.extract.outputs.version }}
runs:
  using: "composite"
  steps:
  - name: "extract project.version attrib content"
    shell: bash
    id: extract
    run: echo "version=$(node -p 'require("${{ inputs.path }}").version')" >> $GITHUB_OUTPUT
