name: Extract project version
runs:
  using: "composite"
  outputs:
    version: "project version"
  steps:
    - name: extract project.version content
      shell: bash
      run: echo "version=$(mvn help:evaluate -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT
