name: Extract project version
runs:
  using: "composite"
  steps:
    - name: extract project.version
      shell: bash
      run: echo "version=$(mvn help:evaluate -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT
