name: Extract project version
outputs:
  version:
    description: "project version"
runs:
  using: "composite"
  steps:
  - name: "extract project.version tag content"
    shell: bash
    id: testVer
    run: echo "version=$(mvn help:evaluate -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT
  - name: "test"
    run: echo "version ${{ steps.testVer.outputs.version }}"
