name: Java code source scan with SonarQube
branding:
  icon: bookmark
  color: green
inputs:
  version:
    description: "npm|mvn project version"
    required: true
runs:
  using: "composite"
  steps:
    - name: create release
      run: gh release create "$version" --repo="$GITHUB_REPOSITORY" --target="${{ github.ref_name }}" --title="v${{ inputs.version }}" --generate-notes
