name: Deploy project 
inputs:
  profile:
    description: "maven profile"
    required: false
runs:
  using: "composite"
  steps:
  - name: deploy
    shell: bash
    run: mvn --batch-mode --no-transfer-progress ${{ inputs.version && format('-P{0}', inputs.version) || '' }} deploy
